kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-view-access
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
--- 
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: web-dev-edit-access
  namespace: web
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]