apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripinsights-ingress-api
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tripinsights.51.104.144.171.nip.io
    http:
      paths:
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/user
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripinsights-ingress-web
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tripinsights.51.104.144.171.nip.io
    http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /
---