apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "{{ .Release.Name }}.{{ .Values.ingressControllerIP }}.nip.io"
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-poi
          servicePort: 80
        path: /api/poi/
      - backend:
          serviceName: {{ .Release.Name }}-trips
          servicePort: 80
        path: /api/trips/
      - backend:
          serviceName: {{ .Release.Name }}-user-java
          servicePort: 80
        path: /api/user-java/
      - backend:
          serviceName: {{ .Release.Name }}-userprofile
          servicePort: 80
        path: /api/user/