apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryyle9462.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminyLe9462"
        - name: SQL_PASSWORD
          value: "aT8ip2Ve8"
        - name: SQL_SERVER
          value: "sqlserveryle9462.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  annotations:service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: user-java