apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryyle9462.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
          name: trips
        env:
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
        - name: SQL_USER
          value: "sqladminyLe9462"
        - name: SQL_PASSWORD
          value: "aT8ip2Ve8"
        - name: SQL_SERVER
          value: "sqlserveryle9462.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: OPENAPI_DOCS_URL
          value: "http://changeme"
        - name: DEBUG_LOGGING
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: trips