apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trips.fullname" . }}
  labels:
    {{- include "trips.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trips.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trips.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "trips.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/trips/healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /api/trips/healthcheck
              port: http
          env:
          - name: SQL_USER
            value: "{{ .Values.sqlConfig.SQL_USER }}"
          - name: SQL_PASSWORD
            value: "{{ .Values.sqlConfig.SQL_PASSWORD }}"
          - name: SQL_SERVER
            value: "{{ .Values.sqlConfig.SQL_SERVER }}"
          - name: SQL_DBNAME
            value: "{{ .Values.sqlConfig.SQL_DBNAME }}"
          - name: PORT
            value: "80"
          - name: CONFIG_FILES_PATH
            value: "/kvmnt"
          - name: OPENAPI_DOCS_URL
            value: "http://changeme"
          - name: DEBUG_LOGGING
            value: "false"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
