apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gord-apis
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: tripinsights.20.191.41.8.nip.io
    http:
      paths:
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi/
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips/
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java/
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/user/